name: alarm_hides_exit
description: "Hive DB를 활용한 알람 앱"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.3.0
  android_alarm_manager_plus: ^3.0.4
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 이미지 asset은 하나 이상의 해상도별 "변형"을 참조할 수 있습니다.
  # https://flutter.dev/to/resolution-aware-images를 참조하세요.

  # 패키지 의존성에서 assets를 추가하는 방법에 대한 자세한 내용은
  # https://flutter.dev/to/asset-from-package를 참조하세요.

  # 앱에 사용자 정의 폰트를 추가하려면 여기 "flutter" 섹션에
  # fonts 섹션을 추가하세요.
  # 이 목록의 각 항목에는 font-family 키와 폰트 asset과
  # 기타 설명자를 제공하는 fonts 키가 있어야 합니다.
  # 예를 들면:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 패키지 의존성의 폰트에 대한 자세한 내용은
  # https://flutter.dev/to/font-from-package를 참조하세요.
